version: "3.9"

services:
  backend:
    build: django
    depends_on:
      - mysql
    volumes:
      - ./django:/opt/docker
      - static_django:/opt/docker/static

  nginx:
    image: nginx:1.21.6
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_django:/usr/share/nginx/html/static

  mysql:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=comunidadealerta
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


volumes:
  static_django:
  