# Generated by Django 4.0.3 on 2022-03-17 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome do bairro', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('nome', models.CharField(help_text='Nome da cidade', max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome da especialidade', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('nome', models.CharField(help_text='Nome do estado', max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('crm', models.CharField(help_text='CRM do medico', max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome do medico', max_length=200)),
                ('especialidade', models.ManyToManyField(to='saude.especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='PostoDeSaude',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome do posto', max_length=200)),
                ('rua', models.CharField(help_text='Nome da rua', max_length=200)),
                ('telefone', models.CharField(blank=True, help_text='Telefone do posto', max_length=100, null=True)),
                ('bairro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='saude.bairro')),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='saude.cidade')),
                ('medico', models.ManyToManyField(to='saude.medico')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='saude.estado'),
        ),
        migrations.AddField(
            model_name='bairro',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='saude.cidade'),
        ),
    ]
