# Generated by Django 4.0.3 on 2022-03-17 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postodesaude',
            name='medico',
        ),
        migrations.CreateModel(
            name='Trabalha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(help_text='Horario de trabalho')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='saude.medico')),
                ('posto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='saude.postodesaude')),
            ],
        ),
    ]
