# Generated by Django 4.0.3 on 2022-03-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0002_remove_postodesaude_medico_trabalha'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='trabalha',
            field=models.ManyToManyField(to='saude.postodesaude'),
        ),
        migrations.DeleteModel(
            name='Trabalha',
        ),
    ]
